name: Update gist with WakaTime stats
on:
  push:
    branches: master

  schedule:
    # 每1小时跑一次
    - cron: "0 */1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e545a860998f072443e9d5aeb8aac3ae
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
